-- Etapa 3: Inserir novos registros na tabela TRU_ANIMELIST
INSERT INTO `personal-anime-data-2024.TRU_DATA.TRU_ANIMELIST`
SELECT
  *
FROM `personal-anime-data-2024.RAW_DATA.RAW_ANIMELIST` AS RAW
WHERE SEASON_YEAR >= (
    SELECT MAX(SEASON_YEAR) - 4
    FROM `personal-anime-data-2024.RAW_DATA.RAW_ANIMELIST`
  )
  AND INITCAP(IFNULL(RAW.TITLE__ENGLISH_, 'NA')) NOT IN (
    SELECT INITCAP(IFNULL(TRU.TITLE__ENGLISH_, 'NA'))
    FROM `personal-anime-data-2024.TRU_DATA.TRU_ANIMELIST` AS TRU
  );
