CREATE OR REPLACE TABLE `personal-anime-data-2024.DMT_DATA.TB_VIS_ANIMELIST` as
SELECT 
    DATE_SEASON_YEAR ,
    NME_TITLE_ENGLISH,
    GENRE_EXPLODED AS DSC_GENRE,  -- Gênero separado por linha
    DSC_COVER_IMAGE,
    NME_SEASON,
    NME_STUDIO,
    NME_SOURCE,
    AVG(KPI_NUM_EPISODES) as KPI_NUM_EPISODES,
    AVG(KPI_AVERAGE_SCORE) as KPI_AVERAGE_SCORE,
    AVG(KPI_POPULARITY) as KPI_POPULARITY,
    AVG(KPI_RECOMMEND_SCORE) as KPI_RECOMMEND_SCORE
FROM `personal-anime-data-2024.REF_DATA.TB_FATO_ANIMELIST`,
    UNNEST(SPLIT(DSC_GENRES, ', ')) AS GENRE_EXPLODED
GROUP BY 1,2,3,4,5,6,7